SE-TINF22B2/G5-DuoGradus

.github/DISCUSSION_TEMPLATE/statusberichte.yml

discussion category form für Statusberichte hinzugefügt

discussion category form für Statusberichte hinzugefügt

---

backend/.gitignore
backend/package-lock.json
backend/package.json
backend/src/app.controller.ts
backend/src/app.service.ts
backend/src/main.ts
backend/test/src/app.controller.spec.ts

The NestJS version was still from when we started with the project. As we did not made any development back then we also never touch the version of the framework.
I updated the version so that we can continue with the development of the application

Updates NestJS to the latest version

---

docs/03-development/testing.md

Add documentation about the testing framework

---

.github/workflows/backend.yml
.github/workflows/frontend.yml

Adds Github Actions that run all test in backend and frontend respectively to verify their general operation on main. The Actions are used for the badges in the readme of the project

Add proper actions to verify that backend and frontend are working on main

---

.github/workflows/backend.yml
.github/workflows/frontend.yml

fix Github Actions

---

.github/workflows/backend.yml
.github/workflows/frontend.yml

further fix for the actions

---

docs/03-development/testing.md

Beschreibung für die verwendeten Testing Frameworks für das Frontend hinzugefügt.

Frontend testing in testing.md hinzugefügt

---

.github/workflows/backend.yml
backend/src/auth/auth.service.ts

fix: Bcrypt not properly imported

---

docs/.vitepress/theme/custom.css
docs/guidelines/project-guideline.md
docs/index.md
docs/project/idea.md

This PR makes small improvements to the documentation

documentation improvements

---

README.md
docs/.vitepress/config.mts
docs/index.md
docs/reports/2023-kw41.md
docs/reports/2023-kw42.md
docs/reports/2023-kw43.md
docs/reports/2023-kw44.md
docs/reports/2023-kw45.md
docs/reports/2023-kw46.md
docs/reports/2023-kw47.md
docs/reports/2023-kw48.md
docs/reports/2024-kw15.md
docs/reports/2024-kw16.md
docs/reports/references.sh
docs/reports/reports.md
docs/reports/reports.sh
docs/reports/template.md

This PR adds the status reports to the docs. This is done to consolidate all project documentation into a single instance.

Add status reports to docs

---

README.md
docs/guidelines/project-guideline.md

This PR adds the language section in the project guideline and therefore closes #96.

Add language section to project guideline

---

docs/public/api/schema.yaml

This PR adds the requested changes to the API scheme, as described in #163.
This closes #163.

Changes to the API schema

---

frontend/src/app/app.component.spec.ts
frontend/src/app/app.component.ts
frontend/src/app/components/atoms/challenge-button/challenge-button.component.spec.ts
frontend/src/app/components/atoms/timer/timer.component.spec.ts
frontend/src/app/components/organisms/challenge-dialog/challenge-dialog.component.spec.ts
frontend/src/app/components/organisms/loginform/loginform.component.spec.ts
frontend/src/app/components/organisms/roadmap/roadmap.component.spec.ts
frontend/src/app/components/organisms/signupform/signupform.component.spec.ts
frontend/src/app/components/organisms/statistic-header/statistic-header.component.spec.ts
frontend/src/app/components/pages/authenticationpage/authenticationpage.component.spec.ts
frontend/src/app/components/pages/mainpage/mainpage.component.spec.ts
frontend/src/index.html

Errors in the test should now be corrected. 
This will close issue #165

Fix: Error in previous test fixed

---

frontend/src/app/app-routing.module.ts
frontend/src/app/app.module.ts

added the missing modules + route for the ranking-page that got merged yesterday
this will close #168

fix: missing modules + route for ranking-page

---

frontend/src/app/app.component.html
frontend/src/app/app.component.ts
frontend/src/app/components/atoms/loader/loader.component.html
frontend/src/app/components/atoms/loader/loader.component.scss
frontend/src/app/components/atoms/loader/loader.component.ts
frontend/src/app/components/organisms/ranking-table/ranking-table.component.spec.ts
frontend/src/app/components/organisms/roadmap/roadmap.component.scss
frontend/src/app/components/pages/mainpage/mainpage.component.html
frontend/src/app/components/pages/mainpage/mainpage.component.ts
frontend/src/app/components/pages/ranking-page/ranking-page.component.spec.ts
frontend/src/app/services/loader.service.spec.ts
frontend/src/app/services/loader.service.ts

A loader has been implemented to indicate that data is being loaded from the backend.

feat: new loader and loaderService 

---

.github/workflows/frontend.yml
frontend/angular.json
frontend/package.json
frontend/src/app/components/pages/profilepage/profilepage.component.html
frontend/src/app/components/pages/profilepage/profilepage.component.spec.ts

This PR fixes the frontend action by adding a ci test configuration to the angular configuration.

Fix Frontend Action

---

.github/workflows/docs.yml
docs/package.json

This PR aligns the GitHub Actions for the `docs` with the ones for the `backend` and `frontend`, introducing a `verify` npm script.

Unified GitHub Actions

---

docs/.vitepress/config.mts
docs/reports/2024-kw19.md

This PR adds the status report for KW19 of 2024.

Status Report KW19

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/enhancement-request.md

Add issue templates

---

docs/.vitepress/config.mts
docs/development/backend/fitness.providers.md

This contains the documentation for the integration with Fitbit (and possible other fitness providers).
The integration is currently in development.

Documentation for Fitness Providers

---

docs/.vitepress/config.mts
docs/development/code-documentation.md

This PR adds a code documentation guideline. It closes #194.
@ reviewers: please read thoroughly because this is an important document. I will only merge with 2 approvals.

Code documentation guideline

---

docs/development/project-guideline.md

This PR closes #191. It adds a paragraph about spoken languages to the project guideline.

Added User Interface to used spoken languages

---

docs/.vitepress/config.mts
docs/reports/2024-kw20.md

This PR adds the Status Report for KW20 of 2024.

Status Report 2024 KW20

---

docs/.vitepress/config.mts
docs/reports/2024-kw20.md
docs/reports/2024-kw21.md

This PR adds the Status Report for KW21 of 2024.

Status Report KW21

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/enhancement-request.md

This PR closes #202. It translates the GitHub Issue Templates into German.

Translated GitHub issue templates

---

docs/development/project-guideline.md

This PR updates the project guideline to reflect the recent changes in the projects infrastructure. It is part of #188.

Updated project guideline

---

.github/pull_request_template.md

**What this PR does/ why we need it?**:
The PR template was written in german where it should be written in english. This PR fixes that.

Translated pull request template

---

docs/.vitepress/config.mts
docs/reports/2024-kw21.md
docs/reports/2024-kw22.md

**What this PR does/ why we need it?**:
This PR adds the status report for KW22.

Status Report KW22

---

docs/reports/2024-kw22.md

Currently our status report lacks some findings we had this week.
None
@OG-NI Please look if everything is correct from your side.

Further changes to Status Report KW22

---

backend/package.json
backend/prisma/migrations/20240605184619_/migration.sql
backend/prisma/schema.prisma
backend/src/app.module.ts
backend/src/app/streaks/streak.controller.ts
backend/src/app/streaks/streak.module.ts
backend/src/app/streaks/streak.service.spec.ts
backend/src/app/streaks/streak.service.ts
backend/src/app/streaks/streak.type.ts
backend/src/db/prisma.module.ts
backend/src/db/prisma.seed.ts
backend/src/db/repositories/streak.repository.ts
backend/test/lib/constants.ts
backend/test/lib/database.constants.ts
docs/public/api/schema.yaml

This PR adds the "Streak" counter and also the documentation on how read the streak via the API.
Closes #208
In Development

Streaks: Initial Implementation and Documentation

---

docs/.vitepress/config.mts
docs/reports/2024-kw23.md

Adds the Status Report KW23 of 2024.
None.
Please feel free to add your thoughts aswell.

Status Report KW23

---

backend/package-lock.json
backend/package.json
backend/src/api/user/patch.user.dto.ts
backend/src/api/user/register.user.dto.ts
backend/src/api/user/user.controller.ts
backend/src/auth/auth.service.ts
backend/src/db/repositories/user.repository.ts
docs/public/api/schema.yaml

This adds an API endpoint for registering new users.
Fixes #207

Endpoint for registering new users

---

backend/src/app/streaks/streak.module.ts
backend/src/app/streaks/streak.service.ts
backend/src/app/tasks/dto/TaskStartStopDTO.ts
backend/src/app/tasks/task.controller.ts
backend/src/app/tasks/task.module.ts
backend/src/app/tasks/task.service.spec.ts
backend/src/app/tasks/task.service.ts
backend/src/app/tasks/tasks/static/task.1.ts
backend/src/app/tasks/tasks/static/task2.ts
backend/src/app/tasks/tasks/static/task3.ts
backend/src/app/tasks/tasks/task.step.ts
backend/src/app/tasks/tasks/task.types.ts

This PR changes the task module, so that tasks now have "points". Those points are added to the user, to allow him to get a streak. The points are added using the streak service, which was introduced by #222.
Closes #210
Closes #209

Add Points for Tasks

---

backend/src/app/tasks/task.module.ts
backend/src/app/tasks/task.service.spec.ts
backend/src/app/tasks/task.service.ts
backend/src/db/repositories/user.repository.ts
backend/src/notification/notification.module.ts
backend/src/notification/notification.service.ts

This sends a notification to the user whenever a task was completed including the title and the points received.
Fixes #243 

Notifications for completed tasks

---

backend/README.md

The backend Readme did not look nearly as good as the frontend Readme. This PR fixes that
Fixes #227 

Improve Backend README

---

docs/.vitepress/config.mts
docs/project/project-takeover.md

Projektübernahme in den docs
Fixes #228 

Added project takeover to docs

---

backend/src/app/streaks/streak.service.ts

The streak is not incremented when points are assigned, so it's not possible to get a streak

fix: streak is not incremented
